name: Format

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check .
